execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set syntax=on
set tabstop=4
set shiftwidth=4
set expandtab
set nowrap
set mouse=a
set splitright
set splitbelow
set autoindent smartindent
set foldmethod=indent
set clipboard=unnamedplus

" neocomplcache
" let g:neocomplcache_enable_at_startup = 1

" Airline
let g:airline_powerline_fonts=1
set laststatus=2

if has("gui_running")
    color badwolf
    set background=dark
    set guifont=Monospace\ 9
    " Remove Toolbar
    set guioptions-=T
    " Remove menu bar
    set guioptions-=m
    " Remove right scrollbar
    set guioptions-=r
    " Remove left scrollbar
    set guioptions-=L
else
    color slate
endif

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType html set ft=htmldjango.html

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

" Ctrl+Backsapce delete before word
imap <C-BS> <C-W>
" Ctrl+l delete current line
imap <C-L> c<ESC>ddi
" Ctrl+d delete after word
imap <C-D> c<ESC>dwi
" NerdTree
map <C-a> :NERDTreeToggle<CR>
map <C-k> :cd %:p:h<CR>

" Copy to clipboard selection (require set clipboard=unnamedplus)
vnoremap <C-c> y
" Paste from clipboard (require sete clipboard=unnamedplus)
" imap <C-p> <ESC>"+pkdd

" Easymontion
let g:EasyMotion_do_mapping = 0 " Disable default mappings
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)

