execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set syntax=on
set tabstop=2
set shiftwidth=2
set expandtab
set nowrap
set mouse=a
set splitright
set splitbelow
set autoindent smartindent
set foldmethod=indent
set clipboard=unnamedplus

" neocomplcache
" let g:neocomplcache_enable_at_startup = 1

" Airline
let g:airline_powerline_fonts=1
set laststatus=2

if has("gui_running")
    color badwolf
    set background=dark
    set guifont=Monospace\ 12
    " Remove Toolbar
    set guioptions-=T
    " Remove menu bar
    set guioptions-=m
    " Remove right scrollbar
    set guioptions-=r
    " Remove left scrollbar
    set guioptions-=L
    " font size functions
    function! FontSizePlus ()
      let l:gf_size_whole = matchstr(&guifont, '\( \)\@<=\d\+$')
      let l:gf_size_whole = l:gf_size_whole + 1
      let l:new_font_size = ' '.l:gf_size_whole
      let &guifont = substitute(&guifont, ' \d\+$', l:new_font_size, '')
    endfunction
    function! FontSizeMinus ()
      let l:gf_size_whole = matchstr(&guifont, '\( \)\@<=\d\+$')
      let l:gf_size_whole = l:gf_size_whole - 1
      let l:new_font_size = ' '.l:gf_size_whole
      let &guifont = substitute(&guifont, ' \d\+$', l:new_font_size, '')
    endfunction
    nmap <C-S-F12> :call FontSizePlus()<CR>
    nmap <C-S-F11> :call FontSizeMinus()<CR>
    nmap <C-S-F10> :set guifont=Monospace\ 12<CR>
else
    color slate
endif

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType html set ft=htmldjango.html

autocmd FileType css setlocal omnifunc=csscomplete#CompleteCSS
autocmd FileType html,markdown setlocal omnifunc=htmlcomplete#CompleteTags
autocmd FileType javascript setlocal omnifunc=javascriptcomplete#CompleteJS
autocmd FileType python setlocal omnifunc=pythoncomplete#Complete
autocmd FileType xml setlocal omnifunc=xmlcomplete#CompleteTags

if strpart(expand('%:p:h'), 0, 20) == '/run/user/1000/gvfs/'
    set noswapfile
endif

" Ctrl+Backsapce delete before word
imap <C-BS> <C-W>
" Ctrl+l delete current line
imap <C-L> c<ESC>ddi
" Ctrl+d delete after word
imap <C-D> c<ESC>dwi
" NerdTree
map <C-a> :NERDTreeToggle<CR>
" Change directory path to current file
map <C-k> :cd %:p:h<CR>
" Indent 4
map <C-S-F4> :set expandtab ts=4 sw=4 ai<CR>
imap <C-S-F4> <ESC>:set expandtab ts=4 sw=4 ai<CR>a
" Indent 2
map <C-S-F2> :set expandtab ts=2 sw=2 ai<CR>
imap <C-S-F2> <ESC>:set expandtab ts=2 sw=2 ai<CR>a
" Exec Python
map <C-S-b> :!python %<CR>

" Copy to clipboard selection (require set clipboard=unnamedplus)
vnoremap <C-c> y
" Paste from clipboard (require sete clipboard=unnamedplus)
" imap <C-p> <ESC>"+pkdd

" Easymontion
let g:EasyMotion_do_mapping = 0 " Disable default mappings
map  / <Plug>(easymotion-sn)
omap / <Plug>(easymotion-tn)
map  n <Plug>(easymotion-next)
map  N <Plug>(easymotion-prev)

" ftp-poseidon
if strpart(expand('%:p:h'), 0, 20) == '/run/user/1000/gvfs/'
  set noswapfile
endif
