execute pathogen#infect()
syntax on
filetype plugin indent on

set number
set syntax=on
set tabstop=4
set shiftwidth=4
set expandtab
set nowrap
set mouse=a
set splitright
set autoindent smartindent
set foldmethod=indent

if has("gui_running")
    color badwolf
    set background=dark
    set guifont=Monospace\ 9
    " Remove Toolbar
    set guioptions-=T
    " Remove menu bar
    set guioptions-=m
    " Remove right scrollbar
    set guioptions-=r
    " Remove left scrollbar
    set guioptions-=L
    " Copy to clipboard selection
    vnoremap <C-c> "*y
else
    color slate
endif

autocmd FileType python set omnifunc=pythoncomplete#Complete
autocmd FileType javascript set omnifunc=javascriptcomplete#CompleteJS
autocmd FileType html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType css set omnifunc=csscomplete#CompleteCSS
autocmd FileType html set ft=htmldjango.html

" Ctrl+Backsapce delete before word
imap <C-BS> <C-W>
" Ctrl+l delete current line
imap <C-L> c<ESC>ddi
" Ctrl+d delete after word
imap <C-D> c<ESC>dwi
